const { sequelize } = require('./src/config/database');

(async () => {
    try {
        await sequelize.authenticate();
        console.log("Connected to DB.");

        const queryInterface = sequelize.getQueryInterface();
        const tables = await queryInterface.showAllTables();
        console.log("Found tables:", tables);

        for (const tableName of tables) {
            console.log(`\nChecking indexes for table: ${tableName}`);
            const [results] = await sequelize.query(`SHOW INDEX FROM \`${tableName}\``);

            const indexesToDrop = [];
            
            results.forEach(row => {
                const name = row.Key_name;
                
                // Heuristic: if it ends in _number, likely a duplicate generated by sequelize
                if (name.match(/_\d+$/)) {
                    if (!indexesToDrop.includes(name)) {
                        indexesToDrop.push(name);
                    }
                }
            });

            if (indexesToDrop.length === 0) {
                console.log(`No duplicate indexes found to drop in ${tableName}.`);
            } else {
                console.log(`Indexes to drop in ${tableName}:`, indexesToDrop);
                for (const indexName of indexesToDrop) {
                    console.log(`Dropping index: ${indexName} from ${tableName}`);
                    try {
                        await sequelize.query(`DROP INDEX \`${indexName}\` ON \`${tableName}\``);
                    } catch (e) {
                        console.error(`Failed to drop ${indexName} from ${tableName}: ${e.message}`);
                    }
                }
            }
        }

        console.log("\nDone checking and dropping duplicate indexes across all tables.");

    } catch (error) {
        console.error("Error:", error.message);
    } finally {
        await sequelize.close();
    }
})();
